ReadSpeaker.ui=function(){var a=null,g=[],q=[],w=!1,p=function(f){f=f||window.event;f.returnValue=!1;if(f=f.originalEvent)f.cancelBubble=!0,f.returnValue=!1;f&&f.preventDefault&&f.preventDefault();f&&f.stopPropagation&&f.stopPropagation()},l=function(){rspkr.log("[rspkr.ui] Attempting to add click events.");var f=$rs.get("."+rspkr.ui.rsbtnClass+" a.rsbtn_play"),a=null;$rs.isArray(f)||(f=[f]);for(var c=0,b=f.length;c<b;c++)if($rs.unregEvent(f[c],"click",ReadSpeakerDefer.clickhandler),a=f[c]?$rs.getAttr(f[c],
"data-rsevent-id"):"_bogus_",rspkr.l.f.eq.store[a]&&rspkr.l.f.eq.store[a].click)rspkr.log("[rspkr.ui] Click event already existed on "+f[c],2);else{$rs.regEvent(f[c],"click",function(h){p(h);window.readpage(this)});rspkr.ui.addFocusHandler(f[c],!0,f[c].parentNode);rspkr.log("[rspkr.ui] Added click event to: "+f[c],1);try{$rs.getAttr(f[c],"role")||$rs.setAttr(f[c],"role","button")}catch(g){rspkr.log("[rspkr.ui] Could not add role attribute.",2)}}},y=function(){rspkr.log("[rspkr.ui] Initiating global callbacks");
rspkr.ui.rsbtnClass=rspkr.cfg.item("ui.rsbtnClass")||"rsbtn";window.readpage=function(a,f){rspkr.ui.initrun&&rspkr.ui.showPlayer(a,f)};window.rshlexit=function(f){rspkr.HL.chunking&&rspkr.HL.chunking.destroy();(void 0===f||"false"===f)&&a.stop();setTimeout(function(){rspkr.c.dispatchEvent("onAfterSyncExit",window)},1E3)};window.rshlinit=m().sync.init;window.rshlsetContent=m().sync.setContent;window.rshlsetId=m().sync.setId;window.rshlsync=function(a,f){for(var c=a.split(","),b=f.split(","),h=0,n=
a.length;h<n;h++)m().sync.execute(c[h],b[h])};window.rshlcontinue=function(){function a(h){if(!rspkr.HL.chunking.entracte.src){var h=encodeURIComponent(decodeURIComponent(rs.cfg.getPhrase(h))),f={},c;for(c in rspkr.c.data.params)rspkr.c.data.params.hasOwnProperty(c)&&(f[c]=rspkr.c.data.params[c]);c=rspkr.Common.data.selectedText;var b=rspkr.Common.data.selectedHTML;rspkr.Common.data.selectedText=h;rspkr.Common.data.selectedHTML="";f.text=h;f.output="audio";h=rspkr.c.buildReadSpeakerCall(f);rspkr.HL.chunking.entracte.src=
h;rspkr.Common.data.selectedText=c;rspkr.Common.data.selectedHTML=b}rspkr.HL.chunking.entracte.volume=parseFloat((rspkr.st.get("hlvol")||100)/100);rspkr.HL.chunking.entracte.play()}if(rspkr.HL.chunking){rspkr.log("[rspkr.ui.rshlcontinue]");rspkr.HL.chunking.chunkEnded=!0;var f=$rs.get("#sync"+rspkr.HL.html5.synclist[rspkr.HL.html5.synclist.length-1][2]),f=$rs.offset(f);if(rspkr.HL.chunking.continueHref){var c=rspkr.cfg.item("cb.chunking.pause",void 0,!0);if(-1==rspkr.HL.chunking.continueTime)if(rspkr.log("[rspkr.ui.rshlcontinue] Waiting for user interaction"),
rs.ui.getActivePlayer().pause(),$rs.addClass(rspkr.ui.getActivePlayer().getContainer(),"rsautopaused"),a("chunkcontinue"),c&&"function"==typeof c)rspkr.log("[rspkr.ui.rshlcontinue] Running custom callback",3),c();else{rspkr.log("[rspkr.ui.rshlcontinue] Showing default continue button");c=document.createElement("div");c.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");$rs.addClass(c,rspkr.ui.rsbtnClass+" rspopup rsresume");var b=$rs.findIn(c,"a");b.removeAttribute("href");$rs.regEvent(b,"click",
function(){rspkr.c.dispatchEvent("onChunkResume",window)});$rs.findIn(b,".rsbtn_text").innerHTML="<span>"+rs.cfg.getPhrase("chunkbutton")+"</span>";document.body.appendChild(c);c.style.display="block";f.left+=15;b=f.left+$rs.width(c)-$rs.width(window);0<b&&(f.left-=b);c.style.left=f.left+"px";c.style.top=f.top+15+"px"}else 0==rspkr.HL.chunking.continueTime?(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay"),rspkr.c.dispatchEvent("onChunkResume",window)):isNaN(rspkr.HL.chunking.continueTime)?rspkr.log("[rshlcontinue] Invalid time parameter!",
3):(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay with "+rspkr.HL.chunking.continueTime+" seconds delay"),5<=rspkr.HL.chunking.continueTime&&a("chunkwait"),c&&"function"==typeof c&&c(rspkr.HL.chunking.continueTime),rspkr.HL.chunking.stall=!0,setTimeout(function(){rspkr.HL.chunking.stall=!1},1E3*rspkr.HL.chunking.continueTime),rspkr.HL.chunking.timer=setTimeout(function(){rspkr.c.dispatchEvent("onChunkResume",window)},1E3*rspkr.HL.chunking.continueTime))}else rspkr.log("[rshlcontinue] No continue href found!")}};
var f=rspkr.c.data.browser;f&&(/iphone|ipad|ios|android/i.test(f.OS)||"android"==f.name.toLowerCase())?$rs.regEvent(document.body,"touchend",function(f){rspkr.c.data.setSelectedText(f);return!0}):($rs.regEvent(document.body,"mousedown",function(f){rspkr.ui.setPointerPos(f);return!0}),$rs.regEvent(document.body,"mouseup",function(a){"opera"===f.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(window,"mouseup",function(a){"opera"===
f.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(document.body,"keydown",rspkr.ui.setPointerPos),$rs.regEvent(document.body,"keyup",function(f){rspkr.c.data.setSelectedText(f);return!0}))},u=function(){document.removeEventListener?document.removeEventListener("click",window.ReadSpeakerDefer.clickhandler,!1):document.detachEvent&&document.detachEvent("onclick",window.ReadSpeakerDefer.clickhandler);if(ReadSpeakerDefer.deferred){var f=
ReadSpeakerDefer.deferred,a=null;if("a"!=f.tagName.toLowerCase()){for(a=f;"body"!=a.tagName.toLowerCase()&&!(a=a.parentNode,"a"==a.tagName.toLowerCase()););f=a}ReadSpeakerDefer.isRSLink(f)&&(rspkr.log("[rspkr.ui] Activating deferred element: "+f),$rs.removeClass(f.parentNode,"rsdeferred"),rspkr.ui.showPlayer(f));ReadSpeakerDefer.deferred=null}},t=null,e=function(){t&&$rs.isVisible(t)&&(rspkr.log("[rspkr.ui.updateFocus] "+t.outerHTML),r(t))},r=function(f){$rs.focus&&("function"==typeof $rs.focus&&
f)&&$rs.focus(f)},c=function(f){if("iconon"==rspkr.st.get("hlicon")&&!w){var a=q.push(new j)-1;q[a].id=a;q[a].show(f);w=!0}},b=function(){"iconon"==rspkr.st.get("hlicon")&&w&&(q.pop().hide(),w=!1)},j=function(){var a=0,c=0,b=null,g=52,e=null,h=null,n=null,D=function(h){h=h||b;$rs.addClass(h,rspkr.ui.rsbtnClass+" rspopup");rspkr.cfg.item("general.useCompactPopupButton")&&$rs.addClass(h,"rscompact")},j=function(a){$rs.unregEvent(b,"mouseout",i);window.clearTimeout(e);var f,c=b.clientWidth+10,g;h=rspkr.ui.showPlayer(n,
b,!0);g=h.getWidth();f=parseInt($rs.offset(b).left);if((f=rspkr.ui.viewport.width+$rs.scrollLeft(document)-f)<g)f=parseInt($rs.css(b,"left"))-(g-(c-10)),$rs.css(b,"left",f+"px");w=!1;$rs.unregEvent(n,"click",j);$rs.regEvent(n,"click",function(a){p(a);return h.restart()});p(a);return!1},i=function(){e||(e=window.setTimeout(function(){m()},rspkr.cfg.item("general.popupCloseTime")||2E3))},k=function(){e&&(window.clearTimeout(e),e=null)},l=function(h,a){var f=document.body.getBoundingClientRect();$rs.css(b,
{top:a-f.top+"px",left:h-f.left+"px",width:g+"px"})},m=function(){$rs.css(b,{display:"none",top:0,left:0});k();q.splice(null,1);w=!1;b.parentElement.removeChild(b)},v=rspkr.c.findFirstRSButton(),b=document.createElement("div");b.id=rspkr.getID();b.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");D();n=$rs.findIn(b,"a.rsbtn_play");n.href=v?v.href:null;if(v=rspkr.cfg.item("general.popupHref"))n.href=v;var v=n.href.match(/lang=([^&;]*)/i).pop(),C=$rs.findIn($rs.get(b),"a.rsbtn_play span.rsbtn_text span");
C&&(C.textContent=C.innerText=rspkr.cfg.getPhrase("listen",v,"en_us"));$rs.setAttr(n,"title",rspkr.cfg.getPhrase("listentoselectedtext",v,"en_us"));$rs.regEvent(n,"click",j);document.body.appendChild(b);return{setPos:l,show:function(h){k(h);if(h&&"none"==$rs.css(b,"display")){var n=b.cloneNode(!0);n.id=rspkr.getID();$rs.css(n,{display:"block",position:"absolute",top:0,left:0});document.body.appendChild(n);g=$rs.outerWidth(n)+3;document.body.removeChild(n);n=h.clientX||h.pageX;h=h.clientY||h.pageY;
c=h>rspkr.ui.pointerY?h-$rs.scrollTop(document)+36>rspkr.ui.viewport.height-46?h-66:h+30:10>h-$rs.scrollTop(document)-66?h+30:h-51;a=10>n-$rs.scrollLeft(document)?n+10:n-$rs.scrollLeft(document)>rspkr.ui.viewport.width-(g+10)?rspkr.ui.viewport.width+$rs.scrollLeft(document)-(g+10):n+0;l(a,c)}$rs.regEvent(b,"mouseout",i);$rs.regEvent(b,"mouseover",k);i(null);D();$rs.css(b,"display","block")},hide:m,id:null}},i={update:function(f,c,b){"hlspeed"===f&&c!==b&&(f=f.replace("hl",""),rspkr.c.converter[f]&&
"function"==typeof rspkr.c.converter[f]&&(c=rspkr.c.converter[f](c)),rspkr.c.data[f]=c,a&&a.stop(),rspkr.pl.releaseAdapter())}},k=function(a,c,b,g,e,h){$rs.css(a,"background-color","rgb("+c+","+b+","+g+")");g<e?(g+=10,window.setTimeout(function(){k(a,c,b,g,e,h)},50)):h&&"function"===typeof h&&h.apply(a,[])},m=function(){return rspkr.XP?rspkr.XP:rspkr.HL};_expand=function(a){"string"==typeof a&&(a=$rs.get(a));$rs.isArray(a)||(a=[a]);for(var c=0;c<a.length;c++)rspkr.ui.Player(a[c]).show(!0)};_animate=
function(){var a=rs.cfg.item("ui.animate");if(a){var c,b=15,g=500;"object"==typeof a?(a.id&&(c=$rs.get(a.id)),a.count&&(b=a.count),a.interval&&(g=a.interval)):"string"===typeof a&&(c=$rs.get(a));if("boolean"===typeof a&&a||$rs.isArray(c)&&0==c.length||!c)c=$rs.get("."+rs.ui.rsbtnClass);$rs.isArray(c)||(c=[c]);var e=b,h=setInterval(function(){0==e&&($rs.removeClass(c,"rsanimate"),clearInterval(h));1==e--%2?$rs.addClass(c,"rsanimate"):$rs.removeClass(c,"rsanimate")},g)}};return{meta:{revision:"3406"},
initrun:!1,init:function(){evt=rspkr.Common.addEvent;ui=rspkr.ui;evt("onAfterModsLoaded",y);evt("onReady",l);evt("onReady",u);evt("onReady",_animate);evt("onSelectedText",c);evt("onDeselectedText",b);evt("onSettingsChanged",i.update);evt("onAfterSyncInit",e);this.initrun=!0;rspkr.Common.dispatchEvent("onUIInitialized");rspkr.log("[rspkr.ui] Initialized!")},addFocusHandler:function(a,c,b){var g=c,e=b,e=e||a;void 0===g&&(g=!0);$rs.focusIn&&"function"==typeof $rs.focusIn&&($rs.focusIn(a,function(){$rs.addClass(e,
"rsfocus");!0===g&&(t=a);rspkr.Common.dispatchEvent("onFocusIn",window,[a,e])}),$rs.focusOut(a,function(){$rs.removeClass(e,"rsfocus");rspkr.Common.dispatchEvent("onFocusOut",window,[a,e])}))},focus:function(a){r(a)},updateFocus:function(){e()},showOverlay:function(c,b){var g=c,e;e=b||a.getContainer();var j=$rs.findIn(e,".rsbtn_status");0===j.length&&(j=document.createElement("span"),j.className="rsbtn_status_overlay",j.innerHTML='<span class="rsbtn_status"></span>',$rs.findIn(e,".rsbtn_exp").appendChild(j),
j=$rs.findIn(e,".rsbtn_status"));$rs.css($rs.findIn(e,".rsbtn_status_overlay"),"display","block");if("nosound"===g)g='<a class="rsbtn_nosound">'+rspkr.cfg.getPhrase("nosound")+"</a>",j.innerHTML=g,(g=$rs.findIn(e,".rsbtn_nosound"))&&$rs.regEvent(g,"click",function(){return a.nosound()});else if("loaderror"===g){var g=rspkr.c.data.getSaveData("link"),h=document.createElement("a");h.className="rsbtn_loaderror";h.innerHTML="[?]";h.href=g;$rs.regEvent(h,"click",function(a){rspkr.ui.Lightbox.show("<iframe src='"+
h.href+"' style='height:100%'></iframe>",null,!1,null,300);p(a)});j.innerHTML=rspkr.cfg.getPhrase("loaderror")||"An error has occurred, try again";j.appendChild(h)}else j.innerHTML=g},settings:i,rsbtnClass:"",addClickEvents:function(){l()},initGlobalCallbacks:function(){y()},showPopupIcon:function(a){c(a)},processDeferred:function(){u()},showPlayer:function(c,b,e){var j;a:{var i=e;rspkr.log("[rspkr.ui.showPlayer]");i=i||!1;if("string"==typeof c)b:{for(var e=$rs.get("a"),h=0,n=e.length;h<n;h++)if(e[h].href&&
e[h].href==c){e=e[h];break b}e=!1}else e=c;e=(h=e)?$rs.closest(h,".rsexpanded"):void 0;e=$rs.hasClass(e,"pre-expanded")?void 0:e;n=rspkr.HL.chunking?rspkr.HL.chunking.currentChunkNumber:1;if(e&&!$rs.isArray(e)&&rspkr.ui.getActivePlayer()&&1==n&&rspkr.ui.getActivePlayer().getContainer()==e)rspkr.log("Player already active, calling Player.restart() instead"),rspkr.ui.getActivePlayer().restart(),j=void 0;else{rspkr.HL.chunking&&rspkr.HL.chunking.destroy();rspkr.HL.chunking&&rspkr.HL.chunking.html5support&&
(rspkr.HL.chunking.entracte=new Audio,rspkr.HL.chunking.entracte.play(),rspkr.HL.chunking.entracte.pause());rspkr.c.dispatchEvent("onBeforeParamsSet",window,[h]);e="string"==typeof c?c:h.href;n=null;"string"==typeof c&&(c=e.match(/readid=[^&]+/gi),n=e.match(/readclass=[^&]+/gi),c&&0<c.length&&rspkr.HL.Restore.Storage.readId.push(c[0].replace("readid=","").split(",")),n&&0<n.length&&rspkr.HL.Restore.Storage.readClass.push(n[0].replace("readclass=","").split(",")));rspkr.c.data.selectedHTML="";rspkr.c.data.setParams(e);
void 0!==$rs.getAttr(h,"data-target")&&null!==$rs.getAttr(h,"data-target")&&(c=$rs.getAttr(h,"data-target"),c=$rs.get(c),"object"===typeof c&&(b=c));b&&!i?(n=$rs.get(b),$rs.addClass(n,rspkr.ui.rsbtnClass+" rsfloating"),rspkr.basicMode&&($rs.removeClass(n,"rshidden"),$rs.addClass(n,rspkr.ui.rsbtnClass+" rsvisible"))):n=$rs.closest(h,"div."+rspkr.ui.rsbtnClass);if(!0===rspkr.cfg.item("survey.allowed"))if(b=rspkr.c.cookie,i=rspkr.cfg.item("survey.cookieName")||"rspkrsurvey",c=rspkr.cfg.item("survey.cookieLifetime")||
15552E6,h=rspkr.c.data.params,"1"===b.readKey(i,"nmbrdisplays")){rspkr.ui.Lightbox.show(rspkr.cfg.item("survey.url")+"?customerid="+h.customerid+"&lang="+h.lang,rspkr.st.r().replaceTokens(rspkr.cfg.item("ui.survey.buttons").join(),{rsSURVEY_BUTTON_CLOSErs:rspkr.cfg.getPhrase("close")}),!0,function(){$rs.regEvent($rs.get("#rssurvey_button_close"),"click",rspkr.u.Lightbox.hide)},500);rspkr.log(b.updateKey(i,"nmbrdisplays","displayed",c),4);j=void 0;break a}else void 0===b.readKey(i,"nmbrdisplays")&&
rspkr.log(b.updateKey(i,"nmbrdisplays","1",c),4);b:{b=n;for(j in g)if(g[j]&&g[j].getContainer&&g[j].getContainer()==b){j=g[j];break b}j=new rspkr.ui.Player(b);g.push(j)}if(a&&a!=j||a&&e!==a.getHref())a.close(!0),rspkr.c.dispatchEvent("onUIClosePlayer",a.getContainer(),[0<rspkr.c.data.selectedText.length?"textsel":"nosel"]);b=(b=a)?b.getID():null;rspkr.c.dispatchEvent("onUIShowPlayer",window,[b,j.getID()]);j.setHref(e);a=j;j.show();j=a}}return j},expand:function(a){_expand(a)},pointerX:0,pointerY:0,
setPointerPos:function(a){rspkr.ui.pointerX=a.pageX;rspkr.ui.pointerY=a.pageY;return!0},viewport:{width:$rs.width(window),height:$rs.height(window)},popups:q,hl:function(a,c){window.setTimeout(function(){k(a,255,255,100,255,c)},200)},scroll:{INTERVAL:null,STEPS:25,scrollToElm:function(a){$rs.isVisible(a)&&this.initScroll(a)},scrollToAnchor:function(a){for(var c=$rs.get("a"),b=null,e=0;e<c.length;e++){var g=c[e];if(g.name&&g.name==a){b=g;break}}this.initScroll(b)},initScroll:function(a){if(a){for(var c=
a.offsetTop,b=a;b.offsetParent&&b.offsetParent!=document.body;)b=b.offsetParent,c+=b.offsetTop;c-=50;rs.cfg.item("ui.autoscrollOffset")&&!isNaN(rs.cfg.item("ui.autoscrollOffset"))&&(c-=rs.cfg.item("ui.autoscrollOffset"));clearInterval(rspkr.u.scroll.INTERVAL);var b=rspkr.u.scroll.getCurrentYPos(),e=parseInt((c-b)/rspkr.u.scroll.STEPS);rspkr.u.scroll.INTERVAL=setInterval(function(){rspkr.u.scroll.scrollWindow(e,c,a)},10)}else document.location.hash=a},getCurrentYPos:function(){return document.body&&
document.body.scrollTop?document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:window.pageYOffset?window.pageYOffset:0},scrollWindow:function(a,c,b){var e=rspkr.u.scroll.getCurrentYPos(),g=e<c;window.scrollTo(0,e+a);a=rspkr.u.scroll.getCurrentYPos();if(g!=a<c||e==a)window.scrollTo(0,c),clearInterval(rspkr.u.scroll.INTERVAL),"string"==typeof b&&(location.hash=b)}},activePlayer:a,getActivePlayer:function(){return a}}}();
ReadSpeaker.ui.Slider=function(){var a=this,g={handleClass:"",width:0,height:0,left:0,top:0,steps:-1,stepsize:-1,dir:"h",initval:-1,drop:null,start:null,dragging:null,click:null,labelDragHandle:"",labelStart:"",labelEnd:"",nudge:1},q={rsid:void 0,parent:void 0,ref:void 0},w=void 0,p=void 0,l=void 0,y=void 0,u=void 0,t=!1,e=0,r=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()};
this.initElement=function(a){if(!t){"string"==typeof a&&(a=document.getElementById(a));a.innerHTML+='<a href="javascript:void(0);" role="slider" class="keyLink" style="display:block; border:0;">&#160;</a>';var b=a.getElementsByTagName("a"),b=b[b.length-1],j=-1<g.steps?g.steps:100;b.relatedElement=a;$rs.setAttr(b,"title",g.labelDragHandle);$rs.setAttr(b,"aria-label",g.labelDragHandle);$rs.setAttr(b,"aria-orientation","h"==g.dir?"horizontal":"vertical");$rs.setAttr(b,"aria-valuemin",0);$rs.setAttr(b,
"aria-valuemax",j);$rs.setAttr(b,"aria-valuenow",g.initval||0);e=g.initval;$rs.regEvent(a,"mousedown",this.startDragMouse);$rs.regEvent(b,"click",function(a){r(a)});$rs.regEvent(b,"keyup",this.startDragKeys);$rs.regEvent(b,"dragstart",function(a){r(a)});$rs.regEvent(a,"touchstart",this.touchStart);$rs.regEvent(q.parent,"mousedown",this.mouseClick)}};this.mouseClick=function(c){if(!t&&!$rs.hasClass(q.ref,"dragged")){var b=a.findPos(c.target),e=c.clientX-(b.left-g.left),c=c.clientY-(b.top-g.top);l=
b.left;y=b.top;b=a.getCurrentVal({left:e,top:c});"function"==typeof g.click&&g.click(b,q);return!1}};this.findPos=function(a){var b=curTop=0;if(a.offsetParent){do b+=a.offsetLeft,curTop+=a.offsetTop;while(a=a.offsetParent);return{left:b,top:curTop}}};this.startDragMouse=function(c){rspkr.log("[rspkr.ui.Slider] startDragMouse");if(!t){a.startDrag(this);var b=c||window.event;w=b.clientX;p=b.clientY;$rs.regEvent(document.body,"mousemove",a.dragMouse);$rs.regEvent(document.body,"mouseup",a.releaseElement)}r(c);
return!1};this.startDragKeys=function(c){rspkr.log("[rspkr.ui.Slider] startDragKeys "+(c||window.event).keyCode);a.startDrag(this.relatedElement);$rs.regEvent(document.body,"keydown",a.dragKeys);$rs.regEvent(document.body,"keypress",a.switchKeyEvents);$rs.addClass(this.relatedElement,"rskeycontrolled");r(c)};this.touchStart=function(c){c=c.originalEvent;rspkr.log("[rspkr.ui.Slider] touchStart");t||(a.startDrag(c.target),w=c.touches[0].pageX,p=c.touches[0].pageY,$rs.regEvent(c.target,"touchmove",a.touchMove),
$rs.regEvent(c.target,"touchend",a.releaseElement));return!1};this.startDrag=function(c){rspkr.log("[rspkr.ui.Slider] startDrag");u&&a.releaseElement();l=c.offsetLeft;y=c.offsetTop;u=c;$rs.addClass(u,"dragged");"function"==typeof g.start&&g.start(q)};this.dragMouse=function(c){c=c||window.event;a.setPosition(c.clientX-w,c.clientY-p);a.valueChanged=!0;return!1};this.touchMove=function(c){r(c);a.setPosition(c.touches[0].pageX-w,c.touches[0].pageY-p);a.valueChanged=!0;return!1};this.dragKeys=function(c){switch((c||
window.event).keyCode){case 37:case 63234:a.valueChanged=!0;e-=g.nudge;break;case 38:case 63232:a.valueChanged=!0;e+=g.nudge;break;case 39:case 63235:a.valueChanged=!0;e+=g.nudge;break;case 40:case 63233:a.valueChanged=!0;e-=g.nudge;break;case 13:case 27:return a.releaseElement(),!1;case 9:return a.releaseElement(),!0;default:return rspkr.log("[rspkr.ui.Slider] return TRUE"),!0}!0===a.valueChanged&&(rspkr.c.dispatchEvent("onUISliderMove"),"function"==typeof g.dragging&&g.dragging(a.getCurrentVal({skipValueCalculation:!0}),
q));r(c);rspkr.log("[rspkr.ui.Slider] ready to return!");return!1};this.setPosition=function(c,b){var e,i=!1;e=c;var k=l,m=g.left,f=g.width,x="left";"v"==g.dir&&(e=b,k=y,m=g.top,f=g.height,x="top");e=k+e;-1<g.stepsize&&((e+m)%g.stepsize?e=g.stepsize*Math.ceil(e/g.stepsize)+m:i=!0);e>f+m?e=f+m:e<m&&(e=m);i||(u.style[x]=e+"px","function"==typeof g.dragging&&g.dragging(a.getCurrentVal(),q))};this.switchKeyEvents=function(){$rs.unregEvent(document.body,"keydown",a.dragKeys);$rs.unregEvent(document.body,
"keypress",a.switchKeyEvents);$rs.regEvent(document.body,"keypress",a.dragKeys)};this.releaseElement=function(){rspkr.log("[rspkr.ui.Slider] releaseElement");$rs.unregEvent(document.body,"mousemove",a.dragMouse);$rs.unregEvent(document.body,"mouseup",a.releaseElement);$rs.unregEvent(document.body,"keypress",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.unregEvent(document.body,"keydown",a.dragKeys);$rs.unregEvent(u,"touchmove",a.touchMove);$rs.unregEvent(u,"touchend",
a.releaseElement);$rs.removeClass(u,"dragged");$rs.removeClass(u,"rskeycontrolled");$rs.removeClass(u,"rsmousecontrolled");var c=a.getCurrentVal();u=null;"function"==typeof g.drop&&!0===a.valueChanged&&g.drop(c,q);a.valueChanged=!1;rs.ui.getActivePlayer()&&rs.ui.getActivePlayer().setProgress();return!1};this.getCurrentVal=function(a){var b,j=g.width;b="left";var i=g.left;"v"==g.dir&&(j=g.height,b="top",i=g.top);var k=-1<g.steps?g.steps:100,j=-1<g.stepsize?g.stepsize:j/k,a=a?a[b]:$rs.css(q.ref,b).replace(/px/i,
"");pos=Math.round(a)-i;b=Math.round(pos/j);"v"==g.dir&&(b=k-b);rspkr.log("[rspkr.ui.Slider] currentval: "+b);return a&&a.skipValueCalculation||isNaN(b)?e=Math.max(Math.min(e,k),0):e=b};return{init:function(c,b){"string"==typeof c&&(c=document.getElementById(c));if(c){var e=c.id||"data-readspeaker-slider-id-"+Math.floor(2E4*Math.random());c.setAttribute&&c.setAttribute("data-readspeaker-slider-id-","data-readspeaker-slider-parent-"+e);var i={width:function(){return $rs.width(c)},height:function(){return $rs.height(c)}};
if("object"==typeof b)for(var k in b)b.hasOwnProperty(k)&&void 0!==g[k]&&(g[k]=b[k]);k=!1;var l;"rsbtn_volume_slider"===c.className&&("jquery"===rspkr.l.f.currentLib()&&1.5>parseFloat(jQuery.fn.jquery))&&(l=c.parentNode.style.display,c.parentNode.style.display="block",k=!0);g.width=i.width();g.height=i.height();k&&(c.parentNode.style.display=l);-1<g.steps&&(g.stepsize=("h"==g.dir?g.width:g.height)/g.steps);i=document.createElement("span");i.setAttribute("data-readspeaker-slider-id-",e);i.className=
g.handleClass||"rsbtn_progress_handle rsimg";c.appendChild(i);q.rsid=e;q.parent=c;q.ref=i;e=$rs.css(i,"left");null!==e&&(g.left=parseInt(e.replace(/px/i,"")));e=$rs.css(i,"top");null!==e&&(g.top=parseInt(e.replace(/px/i,"")));-1<g.initval&&this.jumpTo(g.initval);g.labelStart&&(e=document.createElement("span"),e.className="slider-label-start",e.innerHTML=g.labelStart,c.appendChild(e));g.labelEnd&&(e=document.createElement("span"),e.className="slider-label-end",e.innerHTML=g.labelEnd,c.appendChild(e));
a.initElement(i)}},jumpTo:function(a){if(isNaN(a))return!1;var b=101,e=a;-1<g.steps&&(a=Math.round(a),b=g.steps+1);if(-1<a&&a<b){var i=g.width,k=g.left,l="left";"v"==g.dir&&(i=g.height,k=g.top,l="top",a=b-1-a);q.ref.style[l]=i/(b-1)*a+k+"px";$rs.setAttr($rs.findIn(q.ref,"a.keyLink"),"aria-valuenow",e)}},setCurrentValue:function(a){e=a},getInstance:function(){return q},getContainer:function(){return q.parent},releaseElement:function(){a.releaseElement()},startDragKeys:function(c,b){a.startDragKeys.call(c,
b)},disabled:function(){if(arguments)t=arguments[0];else return t}}};
ReadSpeaker.ui.Player=function(a){var g=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},q=rspkr.getID(),w=this,p=[],l=0,y=!1,u=null,t=!1,e={_play:null,_pause:null,_stop:null,_vol:null,_settings:null,_dl:null,_closer:null,_powered:null,_get:function(b,c){var e,b="_"+b;e=a?this[b]&&0<this[b].length?this[b]:this[b]=$rs.findIn(a,c):null;return e==[]?null:e},play:function(){return this._get("play",
".rsbtn_play")},pause:function(){return this._get("pause",".rsbtn_pause")},stop:function(){return this._get("stop",".rsbtn_stop")},vol:function(){return this._get("vol",".rsbtn_volume")},settings:function(){return this._get("settings",".rsbtn_settings")},dl:function(){return this._get("dl",".rsbtn_dl")},pin:function(){return this._get("pin",".rsbtn_pin")},powered:function(){return this._get("powered",".rsbtn_powered")},closer:function(){return this._get("closer",".rsbtn_closer")},nosound:function(){return this._get("nosound",
".rsbtn_nosound")},setPlayPause:function(a){rspkr.log("[rspkr.ui.Player.setPlayPause("+a+")]");a=a?$rs.getAttr(this.pause(),"data-rsphrase-play"):$rs.getAttr(this.pause(),"data-rsphrase-pause");$rs.setAttr(this.pause(),"title",rspkr.c.decodeEntities(a));$rs.findIn(this.pause(),".rsbtn_btnlabel").innerHTML=a}},r=!1,c=[],b={play:function(){rspkr.c.dispatchEvent("onUIBeforePlay");rspkr.log("[rspkr.ui.handlers.play]");c.progress&&c.progress.disabled(!1);b.setStateClass(a,"rsplaying");rspkr.basicMode&&
b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsplaying");$rs.addClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");e.setPlayPause(!1);if(rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().getContainer()==a)rspkr.pl.play(),t&&rspkr.pl.getProgress.apply(rspkr.pl,[!0,i,w]),rspkr.c.addEvent("onBeforeSyncInit",function(){t=!0;rspkr.pl.getProgress.apply(rspkr.pl,[!0,i,w])}),"flash"===rspkr.pl.adapter&&!rspkr.displog.onVolumeAdjusted&&rspkr.pl.setVolume(parseInt(rspkr.st.get("hlvol")||"100")),
rspkr.c.dispatchEvent("onUIAfterPlay"),rspkr.cfg.execCallback("cb.ui.play",a);else{rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().close();var h=$rs.findIn(a,".rsbtn_play");window.readpage(h)}},pause:function(){rspkr.log("[rspkr.ui.handlers.pause]");b.setStateClass(a,"rspaused");rspkr.basicMode&&b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rspaused");e.setPlayPause(!0);rspkr.pl.pause();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIPause");rspkr.cfg.execCallback("cb.ui.pause",a);rspkr.log("ReadSpeaker.ui.pause")},
stop:function(){rspkr.log("[rspkr.ui.handlers.stop]");c.progress&&c.progress.disabled(!0);b.setStateClass(a,"rsstopped");$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");rspkr.basicMode&&b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped");e.setPlayPause(!0);$rs.setAttr(a,"data-readspeaker-current",0);c.progress&&(c.progress.jumpTo(0),j(0));rspkr.pl.stop();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIStop",a);rspkr.cfg.execCallback("cb.ui.stop",a);(!document.getElementById("rslightbox_contentcontainer")||
!$rs.isVisible(document.getElementById("rslightbox_contentcontainer")))&&e.pause().focus();rspkr.HL.chunking&&1<rspkr.HL.chunking.currentChunkNumber&&(rspkr.HL.chunking.destroy(),rspkr.pl.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter());rspkr.log("ReadSpeaker.ui.stop")},setStateClass:function(a,b){a&&($rs.removeClass(a,"rspaused rsstopped rsplaying"),$rs.addClass(a,b))},vol:function(b){var e=$rs.findIn(a,".rsbtn_volume_container"),g=$rs.findIn(a,".rsbtn_volume"),b=b.originalEvent,f=function(a){var b=
a.originalEvent,b=$rs.closest(b.srcElement||b.originalTarget,".rsbtn_volume_container");if("click"===a.type){if(void 0===b||$rs.isArray(b)&&!b.length)$rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",f),$rs.unregEvent(document.body,"keyup",f)}else"keyup"===a.type&&27===a.keyCode&&($rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",f),$rs.unregEvent(document.body,"keyup",f))};$rs.css(e,"left",g.offsetLeft+"px");$rs.css(e,"display","none"==$rs.css(e,"display")?"block":"none");
"block"===$rs.css(e,"display")?($rs.regEvent(document.body,"click",f),$rs.regEvent(document.body,"keyup",f)):($rs.unregEvent(document.body,"click",f),$rs.unregEvent(document.body,"keyup",f));b&&b.stopPropagation&&b.stopPropagation();b.cancelBubble=!0;g={keyCode:13};b=$rs.findIn(e,".keyLink");try{c.vol.startDragKeys(b,g)}catch(j){rspkr.log("[rspkr.ui.handlers.vol] Error accessing object _sliders['vol']")}return!1},settings:function(){$rs.hasClass(a,"rsplaying")&&this.pause();rspkr.ui.Lightbox.show(rspkr.st.getHTML(),
rspkr.st.getButtons(),!0,function(a){var b=$rs.get("rslightbox_closer"),c=function(){document.removeEventListener?b.removeEventListener("click",c,!1):document.detachEvent&&document.detachEvent("onclick",c);rspkr.c.dispatchEvent("onSettingsClosed",window,[])};$rs.regEvent(b,"click",c);rspkr.ui.addClickEvents();rspkr.c.dispatchEvent("onSettingsLoaded",window,[]);rspkr.cfg.execCallback("cb.ui.settingsopened",a)})},close:function(h){b.pin(!0);var h=h||!1,f=rspkr.pl,g=!1;rspkr.HL.chunking&&rspkr.HL.chunking.destroy();
h||rspkr.cfg.execCallback("cb.ui.beforeclose",a);f.hasOwnProperty("getProgress")&&rspkr.pl.getProgress(!1);f.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter();$rs.setAttr(a,"data-readspeaker-current",0);c.progress&&c.progress.jumpTo(0);$rs.removeClass(a,"rsstopped rsplaying rspaused rsexpanded");if(rspkr.basicMode){var j;(j=$rs.findIn(a,".rsbtn_play"))&&$rs.removeClass(j,"rsexpanded")}$rs.hasClass(a,"rsfloating")&&($rs.removeClass(a,rspkr.ui.rsbtnClass),rspkr.basicMode&&($rs.removeClass(a,
"rsvisible"),$rs.addClass(a,"rshidden")));e.setPlayPause(!0);$rs.hasClass(a,"rspopup")&&(g=!0,$rs.removeClass(a,"rspopup"),$rs.css(a,"display","none"),a.parentNode.removeChild(a));$rs.css(a,"width","auto");delete rspkr.displog.onVolumeAdjusted;h||(rspkr.c.dispatchEvent("onUIClosePlayer",a,["userclick"]),rspkr.cfg.execCallback("cb.ui.close",a),rspkr.log("ReadSpeaker.ui.close: "+a));!h&&!1===g&&rspkr.ui.focus($rs.findIn($rs.get(a),".rsbtn_play"))},dl:function(){$rs.hasClass(a,"rsplaying")&&this.pause();
var b=$rs.getAttr($rs.findIn(a,".rsbtn_play"),"href"),c=b?rspkr.c.data.getSaveData("dialog",b):rspkr.c.data.getSaveData("dialog"),e=!1;rspkr.log("[rspkr.ui.handlers.dl] Savelink: "+c);rspkr.u.Lightbox.show(this.getDlDialog(),this.getDlButtons(),!0,function(){var a=$rs.get("#rsdl_button_accept"),b=$rs.get("#rsdl_button_decline");a&&$rs.regEvent(a,"click",function(b){rspkr.u.Lightbox.hide(b);e="iOS"!==rspkr.c.data.browser.OS&&0<rspkr.c.data.selectedHTML.length?!0:"iOS"!==rspkr.c.data.browser.OS&&!0===
rspkr.cfg.item("general.usePost")?!0:!1;if(!0===e){b=null;if(document.getElementById("dliframe"))b=document.getElementById("dliframe");else{if(document.selection)try{b=document.createElement('<iframe name="dliframe">')}catch(h){b=document.createElement("iframe")}else b=document.createElement("iframe");b.name="dliframe";b.setAttribute("id","dliframe");b.setAttribute("style","display: none; position: absolute;");b.style.display="none";var f=document.getElementsByTagName("body"),g=null;0<f.length&&(g=
f.item(0));if(g)g.appendChild(b);else return}b.src=c;return!1}$rs.setAttr(a,"href",c);return!0});b&&($rs.regEvent(b,"click",function(a){g(a);rspkr.u.Lightbox.hide(a)}),setTimeout(function(){rspkr.ui.focus(b)},200));rspkr.c.dispatchEvent("onDownloadLoaded",window,[])})},pin:function(b){var c=a.id+"_pinnedHome",f=document.getElementById(c);if(!$rs.hasClass(e.pin(),"pinned")&&!b){if($rs.addClass(e.pin(),"pinned"),!f){var b=function(a,b){return window.getComputedStyle?window.getComputedStyle(a)[b]:a.currentStyle?
a.currentStyle[b]:a.style[b]},f=$rs.clone(a,!1,!0),g=a.offsetLeft,j=a.offsetTop;f.style.width=b(a,"width").replace(/[^-\d\.]/g,"")-2+"px";f.style.height=b(a,"height").replace(/[^-\d\.]/g,"")-2+"px";for(var i="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" "),l=0,k;k=i[l];l++){var m=$rs.css(a,k);$rs.setAttr(a,"data-css-"+k,m);m=b(a,k);"auto"!=m&&(f.style[k]=m)}a.style.position="fixed";a.style.left=g-document.body.scrollLeft+"px";a.style.top=j-document.body.scrollTop+
"px";f.className="rsbtn_pinnedHome rsbtn";for(f.id=c;f.hasChildNodes();)f.removeChild(f.lastChild);a.parentElement.insertBefore(f,a)}}else if($rs.hasClass(e.pin(),"pinned")||b)if($rs.removeClass(e.pin(),"pinned"),f){f.parentNode.removeChild(f);i="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" ");for(l=0;k=i[l];l++)m=$rs.getAttr(a,"data-css-"+k),$rs.css(a,k,m)}},getDlDialog:function(){var a=rspkr.cfg.item("ui.dldialog").join("\n"),b={};b.rsTERMS_OF_USE_HEADINGrs=
rspkr.cfg.getPhrase("touheading");b.rsTERMS_OF_USE_BODYrs=rspkr.cfg.getPhrase("toubody");return rspkr.st.r().replaceTokens(a,b)},getDlButtons:function(){var a=rspkr.cfg.item("ui.dlbuttons").join("\n"),b={};b.rsTERMS_OF_USE_ACCEPTrs=rspkr.cfg.getPhrase("touaccept");b.rsTERMS_OF_USE_DECLINErs=rspkr.cfg.getPhrase("toudecline");return rspkr.st.r().replaceTokens(a,b)},nosound:function(){var a=rspkr.c.data.getSaveData("link");$rs.setAttr(e.nosound(),"href",a);return!0}},j=function(b){var b=100<b?100:b,
c=$rs.findIn(a,".rsbtn_progress_played");"object"===typeof c&&$rs.css(c,"width",b+"%");rspkr.cfg.execCallback("cb.ui.progresschanged",a,[b])},i=function(b){if(b.length){var e=parseInt(b[0]),b=parseInt(b[1]),f=0==b?0:Math.round(100*(e/b)),g=$rs.findIn(a,".rsbtn_current_time"),i=$rs.findIn(a,".rsbtn_total_time"),l,m;c.progress&&(c.progress.setCurrentValue(f),r||(c.progress.jumpTo(f),j(f),g&&(g.innerHTML=l=k(e)),i&&(i.innerHTML=m=k(b)),rspkr.cfg.execCallback("cb.ui.timeupdated",a,[l,m])));rspkr.log("[rspkr.player.updateProgress] current time: "+
e+" total time: "+b);$rs.setAttr(a,"data-readspeaker-current",e);$rs.setAttr(a,"data-readspeaker-buffered",b);0<e&&$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading")}},k=function(a){var a=a/1E3,b=parseInt(a%60),c=parseInt(a/60%60),a=parseInt(a/60/60%60);return(10>a?"0"+a:a.toString())+":"+(10>c?"0"+c:c.toString())+":"+(10>b?"0"+b:b.toString())},m=function(){r=!0},f=function(b){rspkr.log("_dropProgress ("+b+")",5);b&&(b=b/100*$rs.getAttr(a,"data-readspeaker-buffered")/1E3,rspkr.pl.setProgress(b));
r=!1},x=function(a){f(a)},A=function(b){rspkr.log("_dropVolume, "+b,5);b=0>b?0:20*b;c.vol&&c.vol.jumpTo(b/20);rspkr.pl.setVolume(b);rspkr.st.set("hlvol",b);rspkr.cfg.execCallback("cb.ui.volumechanged",a,[b]);return!1},B=function(b,e){if("keyLink"===b.className){var f="";$rs.hasClass(e,"rsbtn_volume_handle")?f="vol":$rs.hasClass(e,"rsbtn_progress_handle")&&(f="progress");var g={keyCode:13};c[f].startDragKeys(b,g)}else $rs.hasClass(e,"rsbtn_volume")&&(g={keyCode:13},f=$rs.findIn(a,".rsbtn_volume_container"),
f=$rs.findIn(f,".keyLink"),c.vol.startDragKeys(f,g))},z=function(a,b){if("keyLink"===a.className){var e="";$rs.hasClass(b,"rsbtn_volume_handle")?e="vol":$rs.hasClass(b,"rsbtn_progress_handle")&&(e="progress");c[e].releaseElement();r=!1}};return{init:function(){p.push([this.show,[]])},initVolume:function(){if(!$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))){var b=rspkr.cfg,e=rspkr.st.get("hlvol")||"100",e=5*(parseInt(e)/100);c.vol=new rspkr.ui.Slider;c.vol.init($rs.findIn(a,".rsbtn_volume_slider"),
{handleClass:b.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:b.item("ui.volumeDir")||"v",steps:5,nudge:1,initval:e,dragging:A,click:A,labelDragHandle:b.getPhrase("slidervolumedesc")});b=$rs.findIn($rs.get(a),".rsbtn_volume_handle a");ui.addFocusHandler(b,!1,b.parentNode)}},show:function(h){var h=h?!0:!1,j=$rs.hasClass(a,"rsexpanded");$rs.rsid(a);a.id=q=a.id||rspkr.getID();ui=rspkr.ui;$rs.hasClass(a,rspkr.ui.rsbtnClass)||$rs.addClass(a,rspkr.ui.rsbtnClass);var i=null,i=rspkr.cfg,k=
rspkr.cfg.getPhrases(rspkr.c.data.getParam("lang"));if(0==$rs.findIn(a,".rsbtn_exp").length){var p=$rs.hasClass(a,"rspopup")?i.item("ui.popupplayer"):i.item("ui.player"),i=document.createElement("div");i.className="rsbtn_exp rsimg rspart";i.innerHTML+=p.join("\n");a.appendChild(i)}i=e.pin();p="Explorer"==rspkr.c.data.browser.name&&8>rspkr.c.data.browser.version;$rs.isArray(i)&&0==i.length&&(i=void 0);i&&!p&&rspkr.cfg.item("ui.usePin")?$rs.removeClass(i,"turnedOff"):i&&i.parentElement.removeChild(i);
if(k){i=function(a,b){var c=$rs.findIn(a,".rsbtn_btnlabel");$rs.isArray(c)||(c=[c]);0<c.length&&(c[0].innerHTML=b)};e.pause()&&($rs.setAttr(e.pause(),"data-rsphrase-pause",k.pause),$rs.setAttr(e.pause(),"data-rsphrase-play",k.play),$rs.setAttr(e.pause(),"title",rspkr.c.decodeEntities(k.pause)),i(e.pause(),rspkr.c.decodeEntities(k.pause)));e.stop()&&($rs.setAttr(e.stop(),"title",rspkr.c.decodeEntities(k.stop)),i(e.stop(),rspkr.c.decodeEntities(k.stop)));e.vol()&&($rs.setAttr(e.vol(),"title",rspkr.c.decodeEntities(k.volume)),
i(e.vol(),rspkr.c.decodeEntities(k.volume)));e.settings()&&($rs.setAttr(e.settings(),"title",rspkr.c.decodeEntities(k.settings)),i(e.settings(),rspkr.c.decodeEntities(k.settings)));e.dl()&&($rs.setAttr(e.dl(),"title",rspkr.c.decodeEntities(k.download)),i(e.dl(),rspkr.c.decodeEntities(k.download)));if(e.powered()){var p=$rs.findIn(e.powered(),".rsbtn_btnlabel"),u=k.speechenabled.match(/.*href="([^"]*)"/i).pop(),t=k.newwindow,w=document.createElement("p");w.innerHTML=k.speechenabled;t=(w.innerText||
w.textContent)+(t?" ("+t+")":"");p&&(p.innerHTML=k.speechenabled);$rs.setAttr(e.powered(),"title",t);$rs.setAttr(e.powered(),"data-readspeaker-href",u);p=$rs.getAttr(e.powered(),"data-rsevent-id");(!p||rs.l.f.eq.store[p]&&!rs.l.f.eq.store[p].click)&&$rs.regEvent(e.powered(),"click",function(){window.open($rs.getAttr(this,"data-readspeaker-href"))})}e.closer()&&($rs.setAttr(e.closer(),"title",rspkr.c.decodeEntities(k.closeplayer)),i(e.closer(),rspkr.c.decodeEntities(k.closeplayer)))}k=rspkr.c.data.browser;
(!/safari/i.test(k.name)||!/iphone|ipad|ios/i.test(k.OS))&&$rs.addClass(a,"rs-no-touch");k=$rs.findIn(a,".rsbtn_status_overlay");$rs.isArray(k)||$rs.css(k,"display","none");"fallback"===rspkr.pl.adapter&&(rspkr.ui.showOverlay("nosound",a),$rs.addClass(a,"rsstopped"));$rs.addClass(a,"rsexpanded");if(rspkr.basicMode){var v;(v=$rs.findIn(a,".rsbtn_play"))&&$rs.addClass(v,"rsexpanded")}!y&&!j&&(e.stop()&&($rs.regEvent(e.stop(),"click",function(a){g(a);b.stop()}),ui.addFocusHandler(e.stop())),e.pause()&&
($rs.regEvent(e.pause(),"click",function(c){g(c);$rs.hasClass(a,"rsplaying")?b.pause():($rs.hasClass(a,"rsstopped")||$rs.hasClass(a,"rspaused"))&&b.play()}),ui.addFocusHandler(e.pause())),e.closer()&&($rs.regEvent(e.closer(),"click",function(a){g(a);b.close()}),ui.addFocusHandler(e.closer())),e.vol()&&($rs.regEvent(e.vol(),"click",function(a){g(a);b.vol(a)}),ui.addFocusHandler(e.vol())),e.dl()&&($rs.regEvent(e.dl(),"click",function(a){g(a);return b.dl(a)}),ui.addFocusHandler(e.dl())),e.settings()&&
($rs.regEvent(e.settings(),"click",function(a){g(a);b.settings()}),ui.addFocusHandler(e.settings())),e.pin()&&($rs.regEvent(e.pin(),"click",function(a){g(a);b.pin()}),ui.addFocusHandler(e.pin())),v=rspkr.cfg,$rs.setAttr(a,"data-readspeaker-current",0),$rs.setAttr(a,"data-readspeaker-buffered",0),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_progress_container"))||(c.progress=new rspkr.ui.Slider,c.progress.init($rs.findIn($rs.get(a),".rsbtn_progress_container"),{handleClass:v.item("ui.progressHandleClass")||
"rsbtn_progress_handle rsimg",dir:v.item("ui.progressDir")||"h",nudge:5,start:m,dragging:f,click:x,labelDragHandle:v.getPhrase("sliderseek")}),j=$rs.findIn($rs.get(a),".rsbtn_progress_handle a"),ui.addFocusHandler(j,!1,j.parentNode)),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))||(j=rspkr.st.get("hlvol")||"100",j=5*(parseInt(j)/100),c.vol=new rspkr.ui.Slider,c.vol.init($rs.findIn(a,".rsbtn_volume_slider"),{handleClass:v.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:v.item("ui.volumeDir")||
"v",steps:5,nudge:1,initval:j,dragging:A,click:A,labelDragHandle:v.getPhrase("slidervolumedesc")}),j=$rs.findIn($rs.get(a),".rsbtn_volume_handle a"),ui.addFocusHandler(j,!1,j.parentNode)),rspkr.Common.addEvent("onFocusIn",B),rspkr.Common.addEvent("onFocusOut",z),rspkr.cfg.execCallback("cb.ui.open",a),y=!0);if($rs.findIn(a,".rsbtn_powered")&&(v=$rs.findIn(a,".rsbtn_powered .rsbtn_btnlabel a")))(/Chrome|Safari|Opera/gi.test(rs.c.data.browser.name)||/Explorer/gi.test(rs.c.data.browser.name)&&8<=rs.c.data.browser.version)&&
$rs.regEvent(v,"click",function(a){g(a)}),v.innerHTML='<span class="rsbtn_label_read">Read</span><span class="rsbtn_label_speaker">Speaker</span><span class="rsbtn_label_icon rsimg"></span>';"0"!=$rs.getAttr(a,"data-readspeaker-current")&&(rspkr.pl.releaseAdapter(),$rs.setAttr(a,"data-readspeaker-current",0));"fallback"!==rspkr.pl.adapter&&!h?(b.play(),rspkr.ui.focus(e.pause())):(c.progress&&c.progress.disabled(!0),b.setStateClass(a,"rsstopped"),$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),
"rsloading"),rspkr.basicMode&&b.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped"));h=(h=a)||a;h=$rs.clone(h,!0,!0);h.id=rspkr.getID();document.body.appendChild(h);$rs.css(h,{position:"absolute",top:"0",left:"0",display:"block",width:"auto"});$rs.css(h,"float","none");$rs.addClass(h,"rsexpanded");v=$rs.outerWidth(h)+3;h.style.display="none";document.body.removeChild(h);l=v;isNaN(l)||$rs.css(a,"width",l+(/[Ee]xplorer/.test(ReadSpeaker.c.data.browser.name)?1:0)+"px")},close:function(a){b.close(a)},
stop:function(){b.stop()},nosound:function(){return b.nosound()},pause:function(){b.pause()},play:function(){b.play()},dl:function(a){b.dl(a)},settings:function(){b.settings()},vol:function(a){b.vol(a)},restart:function(){rspkr.log("[rspkr.ui.restart]");b.stop();window.setTimeout(function(){b.play()},500);return!1},updateProgress:function(a){i(a)},setProgress:function(a){f(a)},getContainer:function(){return a},getID:function(){return q},getWidth:function(){return l},setHref:function(a){u=a},getHref:function(){return u}}};
ReadSpeaker.ui.Lightbox=function(){var a=null,g=null,q=null,w=null,p=null,l=null,y,u=[],t=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},e=function(){$rs.css(l,"display","none");var a=$rs.height(window),c=$rs.height(document),e=parseInt($rs.css(document.documentElement,"width")),g=$rs.width(document),m=$rs.absOffset(document.body),f=0,q=0;isNaN(e)&&(e=$rs.width(window));
m.left&&(q=m.left);m.top&&(f=m.top);$rs.css(p,{width:(g>e?g:e)+"px",height:(c>a?c:a)+"px",top:"-"+Math.abs(f)+"px",left:"-"+Math.abs(q)+"px"});$rs.css(l,"display","block");r()},r=function(){var a=$rs.outerWidth(l),c=$rs.outerHeight(l),e=$rs.width(window),g=$rs.height(window),c=y+80+50<g?y+80:g-50;l.style.height=c+"px";$rs.get("#rslightbox_content").style.height=c-80+"px";c>g?(l.style.top=$rs.scrollTop(document)+"px",l.style.marginTop="10px"):(l.style.top=g/2+"px",l.style.marginTop=-(c/2-$rs.scrollTop(document))+
"px");a>e?(l.style.left=$rs.scrollLeft(document)+"px",l.style.marginLeft="0"):(l.style.left="50%",l.style.marginLeft=-(a/2-$rs.scrollLeft(document))+"px")},c=function(a){27===a.keyCode&&rspkr.ui.Lightbox.hide()};return{init:function(){var b=rspkr.pub.Config;a=b.item("ui.overlay.overlayStyles");g=b.item("ui.overlay.contentStyles");q=b.item("ui.overlay.contentTemplate");document.querySelectorAll||(d=document,s=d.createStyleSheet(),d.querySelectorAll=function(a,b,c,e,f){f=d.all;b=[];a=a.replace(/\[for\b/gi,
"[htmlFor").split(",");for(c=a.length;c--;){s.addRule(a[c],"k:v");for(e=f.length;e--;)f[e].currentStyle.k&&b.push(f[e]);s.removeRule(0)}return b});rspkr.log("[rspkr.ui.Lightbox] Heartbeat!")},show:function(b,j,i,k,m){for(var f=0,x=document.body.getElementsByTagName("*"),r;r=x[f];f++)-1!=r.tabIndex&&(u.push([r,r.tabIndex]),r.tabIndex=-1);if(!("Explorer"==rs.c.data.browser.name&&6==rs.c.data.browser.version)){r=document.querySelectorAll("body > *");for(f=0;x=r[f];f++)if(!("rslightbox_overlay"==x.id||
"rslightbox_contentcontainer"==x.id||"script"==x.tagName.toLowerCase())){var B=x.getAttribute("aria-hidden");B&&x.setAttribute("data-original-aria-hidden",B);x.setAttribute("aria-hidden","true")}}b=b||"";i=i||!1;p?(p.style.display="",l.style.display=""):(p=document.createElement("div"),p.id="rslightbox_overlay",l=document.createElement("div"),l.id="rslightbox_contentcontainer",l.innerHTML=rspkr.st.r().replaceTokens(q.join("\n"),{rsLIGHTBOX_CLOSE_LABELrs:rspkr.cfg.getPhrase("close")}),$rs.setAttr(p,
"style",a.join(";")),$rs.setAttr(l,"style",g.join(";")),document.body.appendChild(p),document.body.appendChild(l),rspkr.evt("onSettingsLoaded",{func:rspkr.st.r().handlers.changed.addButtonEvents,context:rspkr.st.r().handlers.changed,params:[this]}));f=$rs.get("rslightbox_closer");rspkr.ui.addFocusHandler(f,!1);$rs.regEvent(f,"click",function(a){t(a);rspkr.ui.Lightbox.hide(a)});$rs.regEvent(p,"click",rspkr.ui.Lightbox.hide);$rs.regEvent(document.body,"keyup",c);if((x=document.documentElement)&&document.all)x.style.overflowX=
x.style.overflowY="hidden";if(b!=w||i)i=rspkr.cfg.getPhrase("close"),$rs.setAttr(f,"title",i),$rs.findIn(f,".rsbtn_btnlabel").innerHTML=i,$rs.get("#rslightbox_content").innerHTML="",$rs.css("#rslightbox_content","height","auto"),/^http/i.test(b)?$rs.findIn("#rslightbox_content","iframe").length||(i=document.createElement("iframe"),i.src=b,i.className="rslightbox-iframe",void 0===m&&(m=2E3),$rs.get("#rslightbox_content").appendChild(i)):"<"==b.substr(0,1)&&($rs.get("#rslightbox_content").innerHTML=
b),$rs.get("#rslightbox_buttons").innerHTML=j,w=b,"ar_ar"==rs.c.data.params.lang&&(-1==l.className.indexOf("rtl")&&(l.className=(l.className+" rtl").replace(/^\s+|\s+$/g,"")),$rs.setAttr($rs.findIn(l,"legend"),"align","right"));y=void 0!==m&&!isNaN(m)?m:!rspkr.basicMode?$rs.get("#rslightbox_content").clientHeight:$rs.get("#rslightbox_content").scrollHeight;b=$rs.findIn("#rslightbox_content",".rsform-row");for(f=0;f<b.length;f++){j=$rs.findIn(b[f],"input, a, select");$rs.isArray(j)||(j=[j]);for(x=
0;x<j.length;x++)rspkr.ui.addFocusHandler(j[x],!1,b[f])}var z=$rs.findIn("#rslightbox_buttons",".rssettings-button-close");rspkr.ui.addFocusHandler(z,!1);$rs.regEvent(z,"click",function(a){t(a)});(b=$rs.findIn("#rsform_wrapper",".rssettings-button-gotobottom"))&&!$rs.isArray(b)&&rspkr.ui.addFocusHandler(b,!1);(b=$rs.findIn("#rslightbox_buttons",".rssettings-button-gototop"))&&!$rs.isArray(b)&&rspkr.ui.addFocusHandler(b,!1);var h=$rs.findIn("#rslightbox_content","input");$rs.isArray(h)&&0<h.length?
setTimeout(function(){rspkr.ui.focus(h[0]);rspkr.Common.addEvent("onFocusIn",function(a){a.className&&$rs.hasClass(a,"rssettings-button-gototop")?rspkr.ui.focus(h[0]):a.className&&$rs.hasClass(a,"rssettings-button-gotobottom")&&rspkr.ui.focus(z)})},200):$rs.isArray(h)||setTimeout(function(){rspkr.ui.focus(h)},200);e();$rs.regEvent(window,"resize",e);"function"==typeof k&&k.apply(this,[l])},hide:function(a){for(;0<u.length;){var g=u.pop();g[0].tabIndex=g[1]}if(!("Explorer"==rs.c.data.browser.name&&
6==rs.c.data.browser.version))for(var a=document.querySelectorAll("body > *"),g=0,i;i=a[g];g++){var k=i.getAttribute("data-original-aria-hidden");k?(i.setAttribute("aria-hidden",k),i.removeAttribute("data-original-aria-hidden")):i.removeAttribute("aria-hidden")}t(a);p.style.display="none";l.style.display="none";$rs.unregEvent(window,"resize",e);$rs.unregEvent($rs.get("#rslightbox_closer"),"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(p,"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(document.body,
"keyup",c);if((a=document.documentElement)&&document.all)a.style.overflowX=a.style.overflowY="auto";rspkr.ui.updateFocus();rspkr.c.dispatchEvent("onSettingsClosed",window,[])},reposition:r}}();
